### ISSUE TITLE
Do not fail if the jobs takes more time

### ISSUE THREAD

**Issue by bzamecnik** [bzamecnik/s3dt-catalog#15]
```
 tasks.update_ed_catalog() from default
776cebb4-412f-4794-b0e8-3ffab8d8744c
Failed 13 minutes ago
Traceback (most recent call last):
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.4/site-packages/rq/worker.py", line 557, in perform_job
    rv = job.perform()
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.4/site-packages/rq/job.py", line 492, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/s3dt-catalog/tasks.py", line 32, in update_ed_catalog
    download_ed_catalog_to_mongo(mongo_uri, catalog_url, counter)
  File "/opt/s3dt-catalog/ed_catalog.py", line 182, in download_ed_catalog_to_mongo
    load_catalog_to_mongo(catalog_xml, item_collection, counter)
  File "/opt/s3dt-catalog/ed_catalog.py", line 79, in load_catalog_to_mongo
    process_catalog(input_xml, process_item)
  File "/opt/s3dt-catalog/ed_catalog.py", line 53, in process_catalog
    xmltodict.parse(input_xml, item_depth=3, item_callback=handle_item)
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.4/site-packages/xmltodict.py", line 246, in parse
    parser.ParseFile(xml_input)
  File "/home/ilan/minonda/conda-bld/work/Python-3.4.5/Modules/pyexpat.c", line 273, in CharacterData
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.4/site-packages/xmltodict.py", line 130, in characters
    def characters(self, data):
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.4/site-packages/rq/timeouts.py", line 51, in handle_death_penalty
    'value (%d seconds).' % self._timeout)
rq.timeouts.JobTimeoutException: Job exceeded maximum timeout value (180 seconds).
```

**Comment by bzamecnik** [comment]
time out can be specified while enqueuing the job:

```
q = Queue()
q.enqueue(task, timeout=timeout_in_seconds)
```

**Comment by bzamecnik** [comment]
Increased from 3 to 10 mins.
