### ISSUE TITLE
ExpatError: reference to invalid character number

### ISSUE THREAD

**Issue by bzamecnik** [bzamecnik/s3dt-catalog#16]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/rq/worker.py", line 557, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.4/site-packages/rq/job.py", line 492, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/s3dt-catalog/tasks.py", line 41, in update_ed_catalog
    download_ed_catalog_to_mongo(mongo_uri, catalog_url, counter)
  File "/opt/s3dt-catalog/ed_catalog.py", line 206, in download_ed_catalog_to_mongo
    load_catalog_to_mongo(catalog_xml, item_collection, counter)
  File "/opt/s3dt-catalog/ed_catalog.py", line 88, in load_catalog_to_mongo
    process_catalog(input_xml, process_item)
  File "/opt/s3dt-catalog/ed_catalog.py", line 59, in process_catalog
    xmltodict.parse(input_xml, item_depth=3, item_callback=handle_item)
  File "/usr/local/lib/python3.4/site-packages/xmltodict.py", line 246, in parse
    parser.ParseFile(xml_input)
xml.parsers.expat.ExpatError: reference to invalid character number: line 5888755, column 1040
```

**Comment by bzamecnik** [comment]
Duplicate of #4.
