### ISSUE TITLE
`update_ed_catalog()` task fails on parsing invalid XML

### ISSUE THREAD

**Issue by bzamecnik** [bzamecnik/s3dt-catalog#4]
```
 tasks.update_ed_catalog() from default
f481f479-eac5-42c5-9bc6-c960d849b75a
Failed 7 minutes ago
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.4/site-packages/rq/worker.py", line 557, in perform_job
    rv = job.perform()
  File "/app/.heroku/python/lib/python3.4/site-packages/rq/job.py", line 492, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/app/tasks.py", line 32, in update_ed_catalog
    download_ed_catalog_to_mongo(mongo_uri, catalog_url, counter)
  File "/app/ed_catalog.py", line 182, in download_ed_catalog_to_mongo
    load_catalog_to_mongo(catalog_xml, item_collection, counter)
  File "/app/ed_catalog.py", line 79, in load_catalog_to_mongo
    process_catalog(input_xml, process_item)
  File "/app/ed_catalog.py", line 53, in process_catalog
    xmltodict.parse(input_xml, item_depth=3, item_callback=handle_item)
  File "/app/.heroku/python/lib/python3.4/site-packages/xmltodict.py", line 246, in parse
    parser.ParseFile(xml_input)
xml.parsers.expat.ExpatError: reference to invalid character number: line 2040689, column 86
```

**Comment by bzamecnik** [comment]
Product identified as `<ProId>1393140</ProId><Code>669038</Code>` contains character reference `&#x1D;` which is not valid.
